Prevent ``KeyError`` exception raised at ``del self._dependencies[prune_task_id]`` during syncing
